Put options ahead of script loading.

diff --git a/with b/with
--- a/with
+++ b/with
@@ -5,6 +5,22 @@ VERSION="0.0.2"
 # usage: with <program>
 # opens an interactive shell instance that automatically prefixes all subsequent commands with program name
 
+#add options here, such as -h, -v
+case ${prefix[*]} in
+  "" )
+    echo "Missing arguments."
+    echo "$helpmsg"
+    exit 1;;
+  "-v" )
+    print_version;;
+  "--version" )
+    print_version;;
+  "-h" )
+    print_help;;
+  "--help" )
+    print_help;;
+esac
+
 # source bash completions
 . /etc/bash_completion
 BASH_COMPLETION_DEFAULT_DIR=/usr/share/bash-completion/completions
@@ -318,22 +334,6 @@ pmpt=${prefix[*]}
                         PROMPT_FORMAT+='%wht%>%nc% '
 
 HISTCONTROL=ignoreboth
-
-#add options here, such as -h, -v
-case ${prefix[*]} in
-  "" )
-    echo "Missing arguments."
-    echo "$helpmsg"
-    exit 1;;
-  "-v" )
-    print_version;;
-  "--version" )
-    print_version;;
-  "-h" )
-    print_help;;
-  "--help" )
-    print_help;;
-esac
 
 setup
 
